In [1]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
import nltk
from nltk.tokenize import sent_tokenize
from tensorflow.keras.layers import Embedding, LSTM, Dense
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np
import regex as re

/Users/navyatrilok/opt/anaconda3/lib/python3.9/site-packages/scipy/__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
/Users/navyatrilok/opt/anaconda3/lib/python3.9/site-packages/pandas/core/computation/expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.8.3' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
/Users/navyatrilok/opt/anaconda3/lib/python3.9/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


In [2]:
import pandas as pd
import regex as re

In [19]:
def file_to_sentence_list(file_path):
    with open(file_path,'r') as file:
        text = file.read()
    
    #Splitting the text into sentences using
    #delimiters like '.','?', and '!'
    sentences = [sentence.strip() for sentence in re.split(r'(?<=[.!?])\s+',text) if sentence.strip()]
    
    return sentences

file_path = '/Users/navyatrilok/Documents/DATASCIENCE/Datasets/DeepLearning/Pizza.txt'
text_data = file_to_sentence_list(file_path)

In [20]:
len(text_data)

79

In [7]:
text_data[0]

'Pizza, the delectable and iconic dish that has transcended borders and captivated taste buds worldwide, is a testament to the extraordinary fusion of flavors, creativity, and cultural significance.'

In [17]:
file = open('/Users/navyatrilok/Documents/DATASCIENCE/Datasets/DeepLearning/Pizza.txt','r')
text_data = file.read()
text[1]

'i'

In [9]:
text_data = ['I am hapy', 'I am going out','I am on leave today and going out']

In [21]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(text_data)
total_words = len(tokenizer.word_index)
total_words

686

In [22]:
tokenizer.word_index

{'the': 1,
 'and': 2,
 'pizza': 3,
 'of': 4,
 'a': 5,
 'to': 6,
 'in': 7,
 'has': 8,
 'its': 9,
 'for': 10,
 'with': 11,
 'it': 12,
 'that': 13,
 'is': 14,
 'as': 15,
 'culinary': 16,
 'from': 17,
 'become': 18,
 'their': 19,
 'have': 20,
 'on': 21,
 'flavors': 22,
 'cheese': 23,
 'toppings': 24,
 'also': 25,
 'delivery': 26,
 'food': 27,
 'people': 28,
 'world': 29,
 'traditional': 30,
 'made': 31,
 'experience': 32,
 'our': 33,
 'pizzerias': 34,
 'dish': 35,
 'diverse': 36,
 'like': 37,
 'crust': 38,
 'delight': 39,
 'symbol': 40,
 'pizzas': 41,
 'more': 42,
 'making': 43,
 'or': 44,
 'iconic': 45,
 'creativity': 46,
 'cultural': 47,
 'italy': 48,
 'an': 49,
 'combinations': 50,
 'ancient': 51,
 'who': 52,
 'ingredients': 53,
 'we': 54,
 'this': 55,
 'style': 56,
 'home': 57,
 'indulgence': 58,
 'beyond': 59,
 'global': 60,
 'inspired': 61,
 'options': 62,
 'those': 63,
 'not': 64,
 'but': 65,
 'together': 66,
 'allowing': 67,
 'just': 68,
 'comfort': 69,
 'local': 70,
 'may': 71,
 '

In [26]:
input_sequences = []
for line in text_data:
    token_list = tokenizer.texts_to_sequences([line])[0]
    for i in range(1,len(token_list)):
        n_gram_sequence = token_list[:i+1]
        input_sequences.append(n_gram_sequence)

In [27]:
tokenizer.texts_to_sequences('i am going out')

[[], [], [5], [], [], [], [], [], [], [], [], [], [], []]

In [28]:
input_sequences

[[3, 1],
 [3, 1, 233],
 [3, 1, 233, 2],
 [3, 1, 233, 2, 45],
 [3, 1, 233, 2, 45, 35],
 [3, 1, 233, 2, 45, 35, 13],
 [3, 1, 233, 2, 45, 35, 13, 8],
 [3, 1, 233, 2, 45, 35, 13, 8, 114],
 [3, 1, 233, 2, 45, 35, 13, 8, 114, 234],
 [3, 1, 233, 2, 45, 35, 13, 8, 114, 234, 2],
 [3, 1, 233, 2, 45, 35, 13, 8, 114, 234, 2, 235],
 [3, 1, 233, 2, 45, 35, 13, 8, 114, 234, 2, 235, 74],
 [3, 1, 233, 2, 45, 35, 13, 8, 114, 234, 2, 235, 74, 115],
 [3, 1, 233, 2, 45, 35, 13, 8, 114, 234, 2, 235, 74, 115, 236],
 [3, 1, 233, 2, 45, 35, 13, 8, 114, 234, 2, 235, 74, 115, 236, 14],
 [3, 1, 233, 2, 45, 35, 13, 8, 114, 234, 2, 235, 74, 115, 236, 14, 5],
 [3, 1, 233, 2, 45, 35, 13, 8, 114, 234, 2, 235, 74, 115, 236, 14, 5, 116],
 [3, 1, 233, 2, 45, 35, 13, 8, 114, 234, 2, 235, 74, 115, 236, 14, 5, 116, 6],
 [3,
  1,
  233,
  2,
  45,
  35,
  13,
  8,
  114,
  234,
  2,
  235,
  74,
  115,
  236,
  14,
  5,
  116,
  6,
  1],
 [3,
  1,
  233,
  2,
  45,
  35,
  13,
  8,
  114,
  234,
  2,
  235,
  74,
  115,
  23

In [29]:
y

NameError: name 'y' is not defined

In [32]:
max_sequence_len = max([len(seq) for seq in input_sequences])
print(max_sequence_len)
input_sequences = np.array(pad_sequences(input_sequences,maxlen=max_sequence_len,padding='pre'))
X,y = input_sequences[:,:-1],input_sequences[:,-1]


#convert target data to one-hot encoding
y = tf.keras.utils.to_categorical(y, num_classes=total_words+1)

40


In [33]:
X.shape,y.shape

((1628, 39), (1628, 687))

In [34]:
y

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [35]:
X

array([[  0,   0,   0, ...,   0,   0,   3],
       [  0,   0,   0, ...,   0,   3,   1],
       [  0,   0,   0, ...,   3,   1, 233],
       ...,
       [  0,   0,   0, ..., 684, 685,   4],
       [  0,   0,   0, ..., 685,   4,  19],
       [  0,   0,   0, ...,   4,  19,  72]], dtype=int32)

In [36]:
y.shape

(1628, 687)

In [43]:
X.shape,y.shape

((1628, 39), (1628, 687))

In [38]:
X[10],y[10].tolist().index(1)

(array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   3,   1, 233,   2,  45,  35,  13,   8, 114, 234,   2],
       dtype=int32),
 235)

In [44]:
model = Sequential()
model.add(Embedding(total_words, 10, input_length=max_sequence_len-1))
model.add(LSTM(128))
model.add(Dense(total_words+1,activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [45]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_2 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [47]:
model.fit(X,y,epochs=100,verbose=1)

Epoch 1/100
51/51 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - accuracy: 0.0355 - loss: 6.3886
Epoch 2/100
51/51 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.0474 - loss: 5.7639
Epoch 3/100
51/51 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.0578 - loss: 5.7153
Epoch 4/100
51/51 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.0621 - loss: 5.6937
Epoch 5/100
51/51 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.0510 - loss: 5.6686
Epoch 6/100
51/51 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.0632 - loss: 5.5927
Epoch 7/100
51/51 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.0694 - loss: 5.5410
Epoch 8/100
51/51 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.0678 - loss: 5.5116
Epoch 9/100
51/51 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.0712 - loss: 5.4665
Epoch 10/100
51/51 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.0762 - loss: 5.2938
Epoch 11/100
51/51 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.0678 - loss: 5.3082
Epoch 12/100
51/51 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step

51/51 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.7882 - loss: 1.2310
Epoch 69/100
51/51 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.8140 - loss: 1.1790
Epoch 70/100
51/51 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.7973 - loss: 1.2168
Epoch 71/100
51/51 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.8032 - loss: 1.1647
Epoch 72/100
51/51 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.8258 - loss: 1.1138
Epoch 73/100
51/51 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.8389 - loss: 1.0853
Epoch 74/100
51/51 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.8309 - loss: 1.0576
Epoch 75/100
51/51 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.8534 - loss: 1.0021
Epoch 76/100
51/51 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.8548 - loss: 0.9840
Epoch 77/100
51/51 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.8593 - loss: 0.9477
Epoch 78/100
51/51 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.8768 - loss: 0.9200
Epoch 79/100
51/51 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - a

In [55]:
seed_text = "Pizza"
next_words = 20

for _ in range(next_words):
    token_list = tokenizer.texts_to_sequences([seed_text])[0]
    token_list = pad_sequences(
    [token_list],maxlen=max_sequence_len-1,padding='pre')
    predicted_probs = model.predict(token_list)
    predicted_word = tokenizer.index_word[np.argmax(predicted_probs)]
    seed_text += " "+ predicted_word
    
print("Next predicted words:", seed_text)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
Next predicted words: Pizza has become a symbol of comfort happiness and celebration and its iconic triangular slices have earned a special place in
